server.port: 9999
# Spring
spring:
    cloud:
        stream:
            default:
               contentType: application/json
            bindings:
               outputPagamento:
                  destination: pagamento.request.queue
                  durableSubscription: true
               outputRecebimento:
                  destination: recebimento.request.queue
                  durableSubscription: true
            binders:
               rabbit:
                  type: rabbit
                  environment:
                    spring.rabbitmq.addresses: ${ORDERING_RABBIT:amqp://teste:teste@localhost:5672/fluxo_caixa}
server:
    port: 8080
